title: UserFrosting Documentation
metadata:
    description: 'The official documentation for UserFrosting, a PHP framework and full-featured user management application.'
    msapplication-config: 'https://learn.userfrosting.com/user/themes/sitetheme/images/browserconfig.xml'
    theme-color: 'ffffff'

taxonomies: [category,tag]
summary:
  size: 300

branches:
    master: master
    develop: develop
    '4.0': '4.0'

redirects:
    /basics/develop-locally-serve-globally: /background/develop-locally-serve-globally
    /basics/overview: /installation
    /basics/installation: /installation
    /basics/requirements: /installation/requirements
    /basics/requirements/basic-stack: /installation/requirements/basic-stack
    /basics/requirements/essential-tools-for-php: /installation/requirements/essential-tools-for-php
    /basics/requirements/develop-locally-serve-globally: /background/develop-locally-serve-globally
    /basics/getting-help: /troubleshooting/getting-help
    /background/client-side: /troubleshooting/debugging
    /background/server-side: /troubleshooting/debugging
    /routes-and-controllers/client-input/overview: /routes-and-controllers/client-input
    /routes-and-controllers/user-input: /routes-and-controllers/client-input
    /routes-and-controllers/user-input/validation: /routes-and-controllers/client-input/validation
    /routes-and-controllers/user-input/csrf-guard: /routes-and-controllers/client-input/csrf-guard
    /routes-and-controllers/user-input/throttle: /routes-and-controllers/client-input/throttle
    /routes-and-controllers/user-input/ajax: /routes-and-controllers/client-input/ajax
    /building-pages: /recipes/creating-a-new-page
    /building-pages/templating-with-twig: /templating-with-twig
    /building-pages/assets: /asset-management
    /building-pages/assets/basic-usage: /asset-management
    /building-pages/assets/asset-bundles: /asset-management/asset-bundles
    /building-pages/assets/compiled-assets: /asset-management/compiled-assets
    /database/extending-the-database: /database/migrations
    /error-handling: /advanced/error-handling
    /other-services: /advanced
    /other-services/cache: /advanced/caching
    /other-services/locator: /advanced/locator
    /other-services/sessions: /advanced/sessions
    /other-services/logging: /advanced/logging
    /other-services/mail: /mail
    /client-side-code/variables-and-templating: client-side-code/exporting-variables
    /forms-and-tables: /client-side-code/components
    /forms-and-tables/forms: /client-side-code/components/forms
    /forms-and-tables/tables: /client-side-code/components/tables
    /security: /background/security
    /advanced/custom-cli: /cli/custom-commands
    /going-live/seo: /background/seo
    /going-live/build: /going-live/vps-production-environment
    /going-live/ssl: /going-live/vps-production-environment/ssl
    /going-live/cron: /going-live/unix-primer-ubuntu
    /recipes/hosting-with-iis: /installation/other-situations/iis
    /contributing/supporting-userfrosting: /contributing
